version: '2'
services:

    # Application container
    app:
        build: .
        restart: unless-stopped
        volumes:
            - ./web/:/app
        depends_on:
            - postgres
            - redis
        environment:
            DEBUG: 'true'

    # Application container
    nginx:
        image: nginx:1.17.10-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - app

    postgres:
        image: onjin/alpine-postgres:9.5
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: hellofresh
            POSTGRES_PASSWORD: hellofresh
            POSTGRES_DB: hellofresh

    redis:
        image: redis:5.0.7
        restart: unless-stopped
        ports:
            - "6379:6379"

